---
# Source: whitelister/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: whitelister
  labels:
    app: whitelister
    group: com.stakater.platform
    provider: stakater
    version: 0.0.2
    chart: "whitelister-0.0.2"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: whitelister
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: whitelister
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: whitelister
      labels:
        app: whitelister
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/whitelister:0.0.2"
        imagePullPolicy: IfNotPresent
        name: whitelister
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: whitelister
      volumes:
      - configMap:
          name: whitelister
        name: config-volume
              
