---
# Source: whitelister/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: whitelister
    group: com.stakater.platform
    provider: stakater
    version: v0.0.12
    chart: "whitelister-v0.0.12"
    release: "whitelister"
    heritage: "Tiller"
  name: whitelister
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: whitelister
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: whitelister
      labels:
        app: whitelister
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/whitelister:v0.0.12"
        imagePullPolicy: IfNotPresent
        name: whitelister
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: whitelister
      volumes:
      - configMap:
          name: whitelister
        name: config-volume
              
