---
# Source: whitelister/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: whitelister
    group: com.stakater.platform
    provider: stakater
    version: v0.0.14
    chart: "whitelister-v0.0.14"
    release: "whitelister"
    heritage: "Tiller"
  name: whitelister
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    app: whitelister
    group: com.stakater.platform
    provider: stakater
    version: v0.0.14
    chart: "whitelister-v0.0.14"
    release: "whitelister"
    heritage: "Tiller"
  name: whitelister-role
rules:
  - apiGroups:
      - ""
    resources:      
      - nodes
      - services
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
    app: whitelister
    group: com.stakater.platform
    provider: stakater
    version: v0.0.14
    chart: "whitelister-v0.0.14"
    release: "whitelister"
    heritage: "Tiller"
  name: whitelister-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whitelister-role
subjects:
  - kind: ServiceAccount
    name: whitelister
    namespace: default
