syncInterval: 10s
removeUnknownIp: true
filter:
  labelName: whitelister
  labelValue: true
ipProviders:
  - name: kubernetes
    params:
      FromPort: 0 
      ToPort: 65535
      IpProtocol: tcp
provider:
  name: aws
  params:
    RoleArn: "arn:aws:iam::111111111111:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
    Region: us-west-2
 