syncInterval: 10s
filter:
  filterType: loadBalancer
  labelName: whitelister
  labelValue: true
ipProviders:
  - name: kubernetes
    params:
      FromPort: 0 
      ToPort: 65535
      IpProtocol: tcp
