syncInterval: 10s
filter:
  labelName: test-whitelister
  labelValue: true
ipProviders:
  - name: git
    params:
      AccessToken: "9a32b3c5aecb788bdc5791dd9cbdafb1ba6876f0"
      URL: "https://github.com/fahad-rauf/whitelister-config.git"
      Config: "config.yaml"
provider:
  name: aws
  params:
    RemoveRule: true
    RoleArn: "arn:aws:iam::449074299682:role/whitelister-developer-assume-role"
    Region: ap-southeast-1
 