syncInterval: 10s
filter:
  labelName: whitelister
  labelValue: true
ipProviders:
  - name: kubernetes
    params:
      FromPort: 0 
      ToPort: 65535
      IpProtocol: tcp
provider:
  name: aws
  params:
    KeepRuleDescriptionPrefix: "DO NOT REMOVE -"
    RemoveRule: true
    RoleArn: <aws-iam-role-arn>
    Region: <aws-region>
 