apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
data:
  config.yaml: |-
    syncInterval: {{ .Values.whitelister.syncInterval }}
    removeUnknownIp: {{ .Values.whitelister.removeUnknownIp }}
    filter:
        labelName: {{ .Values.whitelister.filter.labelName }}
        labelValue: {{ .Values.whitelister.filter.labelValue }}
    ipProviders:
    {{- range .Values.whitelister.ipProviders }}
    - name: {{ .name }}
      params:
      {{- range $key, $value := .params }}
        {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}    
    provider:
        name: {{ .Values.whitelister.provider.name }}
        params:
        {{- range $key, $value := .params }}
          {{ $key }}: {{ $value }}
        {{- end }}