apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
{{ include "whitelister.labels.stakater" . | indent 4 }}
{{ include "whitelister.labels.chart" . | indent 4 }}
  name: {{ template "whitelister.name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "whitelister.labels.selector" . | indent 6 }}
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: {{ template "whitelister.name" . }}
      labels:
{{ include "whitelister.labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: {{ .Values.whitelister.configFilePath }}
        image: "{{ .Values.whitelister.image.name }}:{{ .Values.whitelister.image.tag }}"
        imagePullPolicy: {{ .Values.whitelister.image.pullPolicy }}
        name: {{ template "whitelister.name" . }}
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: {{ template "whitelister.name" . }}
      volumes:
      - configMap:
          name: {{ template "whitelister.name" . }}
        name: config-volume
              